server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8902/eureka/

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:students_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sleuth:
    sampler:
      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  circuitbreaker:
    enabled: false
  
resilience4j:
  retry:
    instances:
      get-all:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true